model: yolov8n-seg.pt
data: configs/hard_distill/cdw_dataset_seg.yaml
epochs: 300
imgsz: 640
batch: 16
device: 0
project: runs/gt
name: data_full
workers: 4
patience: 50
pretrained: true
resume: false
optimizer: auto
lr0: 0.01
close_mosaic: 10
cache: false
amp: true
single_cls: false
cos_lr: false
exist_ok: true
